### ISSUE TITLE
Can someone give me an example of how to evaluate a llama 3 finetuned model using LORA

### ISSUE THREAD

**Issue by jayson1200** [pytorch/torchtune#1067]

**Comment by ebsmothers** [comment]
Hi @jayson1200 thanks for creating the issue. Are you interested in evaluating a Llama3 model that you've already fine-tuned using LoRA? If so you can use our `eleuther_eval` recipe. 

I'll assume that you've downloaded the model via `tune download meta-llama/Meta-Llama-3-8B-Instruct --output-dir /my/dir`. If you finetune the model and place the checkpoint in the same directory, the checkpoint filename should take the form `meta_model_{i}.pt`, where `i` is the epoch number (let's assume you trained for one epoch, in which case it'd be `meta_model_0.pt`. 

Then you should be able to run the command

```
tune run eleuther_eval --config eleuther_evaluation \
checkpointer=torchtune.utils.FullModelMetaCheckpointer \
checkpointer.checkpoint_dir=/my/dir \
checkpointer.checkpoint_files=['meta_model_0.pt'] \
model=torchtune.models.llama3.llama3_8b \
tokenizer=torchtune.modules.tokenizers.torchtune.models.llama3.llama3_tokenizer \ 
tokenizer.path=/my/dir/original/tokenizer.model
```

This will use the config [here](https://github.com/pytorch/torchtune/blob/16b7c8e16ade9ab0dc362f1ee2dd7f0e04fc227c/recipes/configs/eleuther_evaluation.yaml#L4). The overrides I provided are to point to the Llama3-8B model and tokenizer as well as the appropriate paths and format for your checkpoint file.

Regarding the part about LoRA: if you've fine-tuned the model with one of our LoRA recipes already the weights in `meta_model_0.pt` will already contain your learned LoRA weights merged back into the original model.

Hope this helps answer your question, but if anything remains unclear please let me know.

**Comment by jayson1200** [comment]
Is it possible to use the torch tune checkpointer

**Comment by ebsmothers** [comment]
@jayson1200 this is a good question. Right now one of the assumptions of our checkpointers is that the same checkpoint format is used for inputs and for outputs (at least for fine-tuning runs). This means that the use of `FullModelTorchTuneCheckpointer` is kinda rare for fine-tuning, since typically the model weights are downloaded from Hugging Face first, either in HF format or Meta format. (One exception would be if you separately map the downloaded checkpoint into the torchtune format on your local machine after running `tune download`, but this is a bit of extra work.)

But at least for eval, it is possible that you would use `FullModelTorchTuneCheckpointer` if you quantize the model prior to running eval. This is briefly described in the note in [the quantization section](https://pytorch.org/torchtune/main/tutorials/llama3.html#faster-generation-via-quantization) of our Llama3 tutorial -- but basically the quantization algorithms we use do not convert back to Hugging Face formats and so you should always use `FullModelTorchTuneCheckpointer` for evaluation of our quantized models.

Btw this is an area we are working to improve. We want to (a) relax the requirement that input and output formats are always the same (so you can e.g. take in a HF checkpoint and output a torchtune one if you want) and (b) document more clearly when each checkpoint format should be used and how to verify you're using the correct one.

**Comment by ebsmothers** [comment]
@jayson1200 I am gonna close this issue, but if you have any other questions feel free to re-open!
