### ISSUE TITLE
misunderstanding of map the cols in instruct template

### ISSUE THREAD

**Issue by Matrix-X** [pytorch/torchtune#1133]
Hi, I have succeeded to tune the chat message lora model with my custom chat_dataset.

But when I start to tune my instruct data by the [Customizing instruct templates](https://pytorch.org/torchtune/stable/tutorials/datasets.html#customizing-instruct-templates),

 the instruct template only have "instruction" and "input" vars, without the "response" var,  which I get confused.

Also why the sample doesn't have response field in the document?
sample = {
    "instruction": "Classify the following into animals, plants, and minerals",
    "input": "Oak tree, copper ore, elephant",
}

Do I miss something important about the Llama3 finetune concept?

I also tried to watch other finetune way, the instruct template looks like this:
<img width="575" alt="image" src="https://github.com/pytorch/torchtune/assets/317570/5af81be6-b828-40e4-a2d1-4fc8a20de7c3">

Please help me figure it out.

**Comment by RdoubleA** [comment]
Great question. The output is actually directly handled in the `InstructDataset` since typically it is just appended at the end of the template: https://github.com/pytorch/torchtune/blob/6f37d15b2c99d49ca926173455569aa6f8e24d9d/torchtune/datasets/_instruct.py#L93. So you don't need to explicitly format it in the template itself.

I do agree this is a bit confusing. I am actually planning a rework of instruct/chat templates so that the API is more uniform and it is more clear how to apply them.

**Comment by artisanclouddev** [comment]
Thank you for your reply and explaination.

As my understanding, what I need to offer is the custom template content like:
"""

 ### Instruction:

{{instruction}}

### Input:

{{input}}

### Response:

"""

and also take the care of format method to define the "instruciton" and "input" col mapping, right?

I just send the sample format like :

sample = {
"instruction": "Classify the following into animals, plants, and minerals",
"input": "Oak tree, copper ore, elephant",
"output": "xxxxxxxxx",
}


The InstructDataset will handle the output field in my sample automatically. but I must specify the column with "output", am i right?


BTW, I want to use this instruct template for my Q&A model.  I saw there had a StackExchangedPairedTemplate, which look like similiar use case for Q&A, Should I pick this StackExchangedPairedTemplate or still use the default InstructTemplate?

**Comment by RdoubleA** [comment]
Hey @artisanclouddev, yes if you are using the `AlpacaInstructTemplate` you can structure your sample exactly as you specified. If you have different column names you can use `column_map` to make those adjustments. 

You can get the `AlpacaInstructTemplate` for free if you use the `alpaca_dataset` but change the source:
```
dataset:
  _component_: torchtune.datasets.alpaca_dataset
  source: mydataset/onthehub
```
Or use `instruct_dataset` if you need a little more customization:
```
dataset:
  _component_: torchtune.datasets.instruct_dataset
  source: mydataset/onthehub
  template: torchtune.data.AlpacaInstructTemplate
  column_map:
    instruction: new_instruction_col
    input: new_input_col
    output: new_output_col
```

For the Q&A template, If you want to format your text as "Question: {question}\n\nAnswer: " then yes `StackExchangedPairedTemplate` should work. Just replace the template argument above with `StackExchangedPairedTemplate` and adjust `column_map` accordingly. We've been meaning to rename this since it works as a general Q&A template but haven't gotten around to it. But based on the example sample you provided which has both an instruction and input, I think you would still want to use the [Alpaca instruct template](https://github.com/tatsu-lab/stanford_alpaca/blob/main/train.py#L31) if I understand correctly.

**Comment by artisanclouddev** [comment]
thx, noted , i think i know how to customize my template.

Otherwise, as you mentioned above, you will rework the template, I just wonder how long will it take to upgrade new version. For my plan ,I want to make some tutorials about TorchTune LLama3 finetuning on my youtuber channel.

If the waiting time is short, I think I will wait for the new version and spend time to make these videos.

thx again.

**Comment by RdoubleA** [comment]
Hey @artisanclouddev, it may be several weeks before I'm able to rework the templates :) so I'll leave it up to you whether you want to make your tutorial before or after that.

That sounds awesome otherwise though! Let us know if you have any further questions as you make your tutorials.

**Comment by Matrix-X** [comment]
Get it, looking forward to your improved rework news! Thx again!
