### ISSUE TITLE
[Feature] Enable Adapter Only Checkpointing for LoRA

### ISSUE THREAD

**Issue by pbontrager** [pytorch/torchtune#1212]
LoRA recipes don’t need to save the merged checkpoint at each epoch as the much smaller adapter weights plus the original checkpoint is all you need. Checkpointer has an option on save_checkpoint called adapter_only that only saves the adapter weights. This PR would be to update all Lora based recipes to pass adapter_only=true for each epoch except the final one to get a final saved model.

**Comment by spider-man-tm** [comment]
Hi @pbontrager,

Could you assign Issue #1212 to me? Here are the changes I am considering:

- Since the adapter_only option is already implemented in the save_checkpoint methods of each Checkpointer class in torchtune.utils._checkpointing._checkpointer.py, no modifications to this module are necessary.
  - #1210 
- Add the adapter_only option to the four modules in recipes/lora_**.py.
- When the above option is set to True, skip the block of code around
  - https://github.com/pytorch/torchtune/blob/main/recipes/lora_dpo_distributed.py#L508-L527.

**Comment by joecummings** [comment]
@spider-man-tm This sounds like a great plan - thank you for laying it out so clearly! Assigning this issue to you, but feel free to ping @pbontrager or me if there's anything we can do to help.
