### ISSUE TITLE
[feature request] Profiler for other recipes

### ISSUE THREAD

**Issue by gau-nernst** [pytorch/torchtune#1279]
When I searched for "profiler", only these 2 recipes support profiling
- lora_finetune_single_device.py
- lora_finetune_distributed.py

Is there a reason other recipes don't have profling option? In particular, I'm trying to profile single device full finetuning.

**Comment by joecummings** [comment]
We started with those first two recipes in order to prove out the concept, but there's no reason why we cannot add it to the single device full finetuning. 

We'd love to accept a PR if you want to contribute! But it also should be very easy for you to just `tune cp full_finetune_single_device .` and modify the config to make it work with the profiler.
