### ISSUE TITLE
GemmaTransformerDecoder does not have caches_are_enabled() method

### ISSUE THREAD

**Issue by yasser-sulaiman** [pytorch/torchtune#1446]
The generate function here expects the model to be TransformerDecoder which is not the case for gemma leading to an Attribute error when trying to generate with gemma_2B.  

https://github.com/pytorch/torchtune/blob/4fba6cd44c8f24fe4ea3a2cf3a9c03e12fd9f847/torchtune/utils/_generation.py#L141  

```
  File "/home/user/.conda-envs/my_env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/.conda-envs/my_env/lib/python3.10/site-packages/torchtune/utils/_generation.py", line 143, in generate
    incremental_decoding = model.caches_are_enabled()
  File "/home/user/.conda-envs/my_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'GemmaTransformerDecoder' object has no attribute 'caches_are_enabled'
```
Any suggestions on how to solve it?

**Comment by SalmanMohammadi** [comment]
Hey @yasser-sulaiman. Thanks for raising this.

I think the correct solution here would be to remove 'GemmaTransformerDecoder' and instead return an instance of 'TiedEmbeddingTransformerDecoder' from the Gemma component builders. 
This should be pretty straightforward - if you'd be interested in contributing this I'd be happy to guide you through it! Otherwise I can get to it soon.

**Comment by SalmanMohammadi** [comment]
Hey @yasser-sulaiman, this should now be fixed when you update to the latest torchtune nightly.

**Comment by yasser-sulaiman** [comment]
thank you for the quick fix
