### ISSUE TITLE
Qwen 2.5 is here, Request for adding a model

### ISSUE THREAD

**Issue by vanshnawander** [pytorch/torchtune#1624]
The Qwen team has released qwen 2.5 base, coder, math models. They seem very promising. Requesting Team to add this model in torchtune.
```[tasklist]
### Tasks
```

**Comment by ebsmothers** [comment]
Hi @vanshnawander thanks for creating the issue. I took a quick look, seems like the architecture should be mostly unchanged. In that case we can reuse the model builders from Qwen2 [here](https://github.com/pytorch/torchtune/tree/main/torchtune/models/qwen2). It should be similar for the tokenizer but there are additional special tokens, along with minor changes to the chat template. I'm going to tag this as community help wanted since we'd love to have someone help out with this. cc @fyabc who added Qwen2 in case I'm missing any important details here.

**Comment by fyabc** [comment]
@ebsmothers Hi, thank you for you comments! Qwen2.5 only need to update tokenizer with new special tokens and chat template. I will take a look at this.

**Comment by krammnic** [comment]
As there is no updates here, I can take a look at it.
