### ISSUE TITLE
[RFC] Supporting KV-cache toggling

### ISSUE THREAD

**Issue by SalmanMohammadi** [pytorch/torchtune#1675]
### Problem

Currently, when we use `model.setup_caches()`, KV-caches are always updated for every subsequent forward pass on the model. We have valid use cases for using `model.setup_caches()`, but then not updating the KV-cache on forward passes. The most immediate use-case we have for this is in the eval recipe (see https://github.com/pytorch/torchtune/issues/1621). When specifying multiple tasks in the recipe:
- If one task is a generation task and another a log-likelihood task **and**
- The generation task is evaluated before the log-likelihood task **and**
- KV-cacheing is enabled

Then, KV-cacheing will still be enabled for the log-likelihood task which is incorrect behaviour for a number of reasons. In this example, we have two forward passes occurring, one with KV-cacheing enabled, one with KV-cacheing disabled.

Another use case is for my work on improving our RLHF offerings.
1) For the current PPO recipe, the overall structure looks something like:
```python
batch = batch.to(device)
with torch.no_grad():
    ...
    completions = policy_model.generate(...)

loss = self._ppo_step(completions, policy_model, ...)
loss.backward()
optimizer.step()
```
This isn't 1:1 but you get the gist. Here, we have two kinds of forward passes: one under `torch.no_grad()` with KV-cacheing, and one with `requires_grad=True` and without KV-cacheing (infact, we should never really have the case where `requires_grad=True` + KV-cacheing, but this part is kind of relevant for compile).

2) For a LoRA PPO recipe I've been working on, the structure is a bit different:

```python
batch = batch.to(device)
with torch.no_grad():
    ...
    completions = policy_model.generate(...)
    with torchtune.modules.peft.disable_adapter(policy_model):
        ref_logits = policy_model(completions)

loss = self._ppo_step(completions, policy_model, ...)
loss.backward()
optimizer.step()
```

So, now three kinds of forward passes: two under `torch.no_grad()`: one with KV-cacheing and one without, and one with `requires_grad=True` and without KV-cacheing.

We want to support these use-cases in a compile friendly manner.

#### 1) Context managing KV-cacheing

To me this feels like the most user-friendly solution. We define a context manager like:
```python
@contextlib.contextmanager
def enable_kv_cache(model):
    if not model.caches_are_enabled():
        raise ValueError()
    for layer in model.layers:
        layer.attn.cache_enabled = True
    try:
        yield
    finally:
        for layer in model.layers:
            layer.attn.cache_enabled = False
```

Which relies on a small modification to `MultiHeadAttention`:
```python

class MultiHeadAttention(...):
    def __init__(...):
        ...
        self.cache_enabled = False

    def forward(...):
        ...
        if self.kv_cache is not None and self.cache_enabled:
            k, v = self.kv_cache.update(k, v)
```
The UX for this change would rely on users always having to use `with enable_kv_cache(model):` if they wanted to use KV-cacheing. This is nice because the behaviour is quite explicit. However, specifically for the eval recipe, KV-cacheing is configurable so we maybe don't want to be erroring out. Two options:

1) inspired by `torch.inference_mode(mode: bool)`
```python
@contextlib.contextmanager
def kv_cache_mode(model, mode=True):
    if not model.caches_are_enabled():
        raise ValueError()
    for layer in model.layers:
        layer.attn.cache_enabled = mode
    try:
        yield
    finally:
        for layer in model.layers:
            layer.attn.cache_enabled = not mode 


with kv_cache_mode(self._model, mode=self._enable_kv_cache)
    toks, _ = generation.generate(
        self._model,
        maybe_padded_context,
        max_generated_tokens=self.max_gen_toks,
        temperature=temperature,
        top_k=None,  # do_sample is not supported currently
        stop_tokens=self._tokenizer.stop_tokens,
    )
```

I'm not 100% sure about this one because I can't imagine many use cases when `model.caches_are_enabled=True` but `mode=False`. Maybe if your default is inference/KV-cacheing and you want to disable it for a single pass? 

2) Don't error out on `model.caches_are_enabled`. If you try using this without `setup_caches`, this is a no-op and nothing will happen:
```python
@contextlib.contextmanager
def kv_cache_mode(model):
    if not model.caches_are_enabled():
        # maybe warn here?
        yield
    for layer in model.layers:
        layer.attn.cache_enabled = True
    try:
        yield
    finally:
        for layer in model.layers:
            layer.attn.cache_enabled = False 
```

I can confirm the above solutions work with compile (I reserve the right to retract this claim in light of any future knowledge).

#### 2) Rely on `inference_mode`

We could differentiate forward passes which require KV-cacheing by using `torch.inference_mode()` (like we currently decorate `_generation.generate` with). Then, the change would simply be:
```python

class MultiHeadAttention(...):
    def __init__(...):
        ...


    def forward(x, ...):
        ...
        if self.kv_cache is not None and x.is_inference():
            k, v = self.kv_cache.update(k, v)
```
However, this will only work with compile with nightlies/until next release (see https://github.com/pytorch/pytorch/pull/136450).

This is a very minimal change but **very non-obvious**, so I don't really like it. Open to thoughts though.

**Comment by joecummings** [comment]
This is an incredibly well thought out RFC - the code examples are extremely helpful

**Comment by joecummings** [comment]
Okay so responding to idea number 1: 

I think you're absolutely correct that being explicit is better than not being explicit; however, I am having trouble wrapping my head around the notion of having to do 2 steps in order to utilize the KV Cache. In my mind, once I call `model.setup_caches()`, it should work w/ KV-Caching going forward. My question would be: **Is there any reason why this can't be done ONLY on the model level?**

Here's what I mean: `model.setup_caches()` creates a KV cache and the model will continue to use it. Then we introduce another API called `model.delete_caches()` that completely removes the KV cache from the model. Everything is kept at the model level instead of a toggling in the forward. 

```python

class _LLMEvalWrapper(HFLM):
	...
	
	loglikelihood_rolling(self, input_ids):
		if model.caches_are_enabled():
			model.delete_caches()
		# Run loglikelihood code
		
	generate_until(self, input_ids):
		model.setup_caches()
		# Run generate code
```

To ask the above question another way: **Is there anytime where we want to truly toggle using the kv cache on/off in order to keep the KV cache state?** If there is, then this approach won't work. If not, then we should just `delete_caches()` and `setup_caches()` when we want to change the model caching state. Need your input here on the RLHF stuff that I don't understand super well.

> Side note: Completely agree that hiding this behind `inference_mode` is not the right way to go unless we want a bunch of users super confused.

**Comment by SalmanMohammadi** [comment]
Thanks so much for your response.

I also considered simply tearing down and re-setting-up caches instead of placing the burden on the user to enable them - which, you're right, through two separate mechanisms! It's a bit clunky. My main concern here was around overhead in these operations. For example, on my M1 Mac and using Llama3.1 8B, here's some timings for setting-up and tearing down caches (where `model.delete_caches()` just sets KV-caches on attention layers to `None`:
```bash
bsz=4, decoder_max_seq_len=4096
Mean setup time (100 runs): 0.634s
Mean teardown time (100 runs): 0.1146s
---------------
bsz=4, decoder_max_seq_len=2048
Mean setup time (100 runs): 0.125s
Mean teardown time (100 runs): 0.03s
---------------
bsz=8, decoder_max_seq_len=4096
Mean setup time (100 runs): 1.77s
Mean teardown time (100 runs): 0.299s
---------------
bsz=8, decoder_max_seq_len=2048
Mean setup time (100 runs): 0.533s
Mean teardown time (100 runs): 0.108s
```
So, scaling quite poorly with batch-size, less so with `max_seq_len`.

We're shaving minimal time here in the eval recipe. For PPO, we'd be performing this operation on the order of magnitude of 1e5 times, which is starting to introduce pretty significant overhead - for example, I use a batch size of 32 for one PPO recipe. 

You're correct that there's pretty much no cases I can think of where you'd want to toggle the state without resetting it. We could try investigate how to reduce the overhead in setup times. Alternatively, I could suggest a rather heavy-handed approach to minimize the number of function calls a user needs to make:

1) `MultiHeadAttention.setup_caches` will always perform
```python
    self.kv_cache = ...
    self.cache_enabled = True
```

This means you don't need to use the context manager if you don't want to - you can just `setup_caches` and be on your merry way.
 
2) We slightly overload our context manager as so:
```python
@contextlib.contextmanager
def kv_cache_mode(model, decoder_max_seq_len=None, encoder_max_seq_len=None):
    if not model.caches_are_enabled():
        model.setup_caches(decoder_max_seq_len, encoder_max_seq_len)
    for layer in model.layers: 
        # we need to do this step if model has caches already setup but potentially not enabled 
        layer.attn.cache_enabled = True
    try:
        yield
    finally:
        for layer in model.layers:
            layer.attn.cache_enabled = False 
        model.reset_caches()
```
And then you can just wrap any generation code `with kv_cache_mode(self._model, self._max_seq_len):` without needing to make a call to `setup_caches` beforehand, or `reset_caches` after. We can keep the underlying mechanisms for users who want more control or don't need this toggling behaviour.

**Comment by joecummings** [comment]
This is helpful context and I'm still formulating a response, but I'm curious if you have times for `reset_caches()` b/c as I understand it, you'd still need to be calling that in your PPO recipe on every new batch.

**Comment by joecummings** [comment]
If the bottleneck is really in the teardown (setup is unavoidable I believe), then we could opt for a similar approach to HF:

```python
batch = batch.to(device)
with torch.no_grad():
    ...
    kv_cache = KVCache(batch_size=8, decoder_max_seq_len=2048)
    completions = generate(policy_model, kv_cache, ...)
    del kv_cache

loss = self._ppo_step(completions, policy_model, ...)
loss.backward()
optimizer.step()
```

Advantages:
* No costly teardown operation
* Very clear to the user what's happening

Cons:
* Would require a large refactor

**Disclaimer**: This is me throwing things at the wall as I try to firmly grasp this situation for RLHF

**Comment by SalmanMohammadi** [comment]
The setup is more of a bottleneck in this scenario since ordinarily we would only be calling `setup_caches` once, rather than for every generation step, right?

**Comment by SalmanMohammadi** [comment]
> refactor
```haskell
⠀⠀⠀⠀⠀⠀⠀⣠⠔⠚⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠑⠒⢤⡀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⣠⠖⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠳⣄⠀⠀⠀⠀
⠀⠀⢠⡞⠁⠀⠀⠀⠀⠀⢀⡀⠀⠀⠀⠀⠀⠀⢀⡀⠀⠀⠀⠀⠀⠀⠱⣄⠀⠀
⠀⡠⠃⠀⠀⠀⠀⠀⠀⣠⣿⡇⠀⠀⠀⠀⠀⠀⠸⣿⣆⠀⠀⠀⠀⠀⠀⠈⢦⠀
⢰⠁⠀⠀⣀⣤⣤⣶⣾⡿⠿⠤⣀⠀⠀⠀⠀⢀⡤⠿⠿⣿⣶⣦⣤⣀⠀⠀⠀⠇
⡇⠀⠀⠀⠙⡿⠛⠉⠀⣀⡀⠀⠈⠳⡀⢀⡴⠁⠀⠀⣀⡀⠈⠙⢻⠋⠀⠀⠀⢸
⡇⠀⠀⠀⢸⠁⠀⢠⣾⣿⣿⡆⠀⠀⡇⢸⠀⠀⢰⣿⣿⣿⡆⠀⠈⡇⠀⠀⠀⢸
⡇⠀⠀⠀⠘⡆⠀⠈⠿⢿⠿⠃⠀⠀⡇⠸⡀⠀⠘⠿⡿⠿⠃⠀⢀⠇⠀⠀⠀⢸
⡇⠀⠀⠀⠀⠘⠦⡀⠀⠀⠀⢀⡠⠊⠀⠀⠑⢄⣀⠀⠀⠀⢀⡤⠊⠀⠀⠀⠀⢸
⡅⠀⠀⠀⠀⠀⠀⠈⠉⠒⠋⠉⠀⠀⠀⠀⠀⠀⠉⠉⠚⠋⠁⠀⠀⠀⠀⠀⠀⢸
⠸⡄⠀⠀⠀⠀⠀⠀⠀⠀⣴⣶⣶⣶⣶⣶⣶⣶⣶⣦⠀⠀⠀⠀⠀⠀⠀⠀⠀⠆
⠀⠙⣄⠀⠀⠀⠀⠀⠀⠀⠈⠉⠉⠉⠉⠉⠉⠉⠉⠁⠀⠀⠀⠀⠀⠀⠀⡴⠋⠀
⠀⠀⠈⢦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡘⠃⠀⠀
⠀⠀⠀⠀⠙⢦⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡴⠋⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠑⠢⠤⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⠤⠔⠊⠃⠀⠀⠀⠀⠀⠀
```

**Comment by felipemello1** [comment]
Great RFC!

I thought of two things:
1. Not tearing down the cache may mean having a constant memory allocated that may impact training. Not sure here about the actual impact, specially if our kv cache is quantized, for example.
2. Instead of context_manager, can this just be an argument in generate (sorry if this is a dumb question)?

```
toks, _ = generation.generate(
        self._model, use_kv_cache=True)
```

**Comment by ebsmothers** [comment]
OK here comes my genius flyby comment after looking at this for 5 minutes.. (jk I have read through all the context now and think I have some idea of the challenges). First, in my opinion the context manager is the way to go here. It's explicit and gives exit conditions, which is exactly what we want. It sounds like there are cases where it's advantageous for the context manager to also handle the teardown of the cache (e.g. if we're memory constrained), but cases where we definitely don't want it (like PPO). So cop-out suggestion: why not support both? 

1) `with enable_persistent_kv_cache` assumes the KV cache has already been set up (if not it will error), no need to pass any args that would be needed on setup. On exit we call reset but don't tear down
2) `with enable_kv_cache` (or some other, slightly more explicit name) sets up the KV cache (so needs batch size, seq len, etc args) and tears it down on exit

Best of both worlds 😃 (unless I'm missing something obvious or oversimplifying).


A secondary point (and maybe I am overengineering here), but it always bothers me when we do stuff like 

```
for layer in model.layers: 
	layer.attn....
```

Why not just define a clear contract on which modules are KV cacheable? Think like our usage of the `AdapterModule` Protocol for PEFT layers and then an iteration like [this](https://github.com/pytorch/torchtune/blob/0a3762d058fd9d860606a3a6bbebf71ac593ab5c/torchtune/modules/peft/_utils.py#L51-L52). Anyways, don't want to derail this particular RFC because like I said, it's a secondary point.
