### ISSUE TITLE
wikitext_dataset has no posibility to be packed.

### ISSUE THREAD

**Issue by krammnic** [pytorch/torchtune#1788]
```
def wikitext_dataset(
    tokenizer: ModelTokenizer,
    source: str = "EleutherAI/wikitext_document_level",
    subset: str = "wikitext-103-v1",
    max_seq_len: Optional[int] = None,
    packed: bool = False,
    filter_fn: Optional[Callable] = None,
    split: str = "train",
    **load_dataset_kwargs: Dict[str, Any],
) -> Union[TextCompletionDataset, PackedDataset]:
```

packed is unused in this function(should be condition and possibility to pack). Therefore, this typehint is also incorrect: `Union[TextCompletionDataset, PackedDataset]`.

**Comment by krammnic** [comment]
cc: @RdoubleA

**Comment by RdoubleA** [comment]
Hm, the packed argument should've been passed into `text_completion_dataset`. It might have been left out purposely because of the size of the dataset. In which case, we have two approaches:
1. Removed the packed argument and update the typehint
2. Keep the packed argument and pass into `text_completion_dataset`, verify that it packs within a reasonable amount of time

**Comment by krammnic** [comment]
Ok, then I will check second variant and if the amount of time is reasonable I will add checks simillary as in other datasets. In another case we should change inconsistent typehints.

**Comment by krammnic** [comment]
The time required to proceed it seemed reasonable to me. Reproducible example:
```
from torchtune.datasets import wikitext_dataset
from torchtune.modules.tokenizers import SentencePieceBaseTokenizer

tokenizer = SentencePieceBaseTokenizer("spm.model")
tokenizer.max_seq_len = 2048
    
dataset = wikitext_dataset(
    tokenizer, packed=True
)
```
Will open PR.
