### ISSUE TITLE
Support for activation offloading pre-fetching?

### ISSUE THREAD

**Issue by shuy98** [pytorch/torchtune#1905]
cc: @janeyx99

The activation offloading feature is fantasic! I wonder if it's possible to support pre-fetching during backward pass? Namely, copy the tensors back to GPU a little earlier so the backward pass doesn't need to wait for it. Thanks!

**Comment by janeyx99** [comment]
Hi! We currently have heuristics to do _implicit_ prefetching, meaning we expect the on-loading in the backward to run ahead of the compute stream. Doing explicit prefetching would require knowing the next node that happens, which is hard to predict especially in a multithreaded setting.

Are you seeing lots of missing overlap in the backward?

**Comment by qsh-zh** [comment]
Hi @janeyx99 @felipemello1 @joecummings 

Do we have any documentation, and could you also point me to the code location for the feature that supports “heuristics for implicit prefetching, where we expect the on-loading in the backward pass to run ahead of the compute stream”?

I’d like to understand how we can achieve something similar to what’s shown in the following figure.

<img width="1333" height="500" alt="Image" src="https://github.com/user-attachments/assets/79a62cc3-28bd-4cfb-8cb2-ddded15c08ad" />

**Comment by janeyx99** [comment]
@qsh-zh sorry for the delayed response--i just got back from vacation. The code for offloading is here: https://github.com/pytorch/torchtune/blob/main/torchtune/training/_activation_offloading.py#L24. Note that there is no explicit prefetching, but we anticipate that the CPU will run ahead of the GPU and thus prefetch things properly. What this means is that we don't have an explicit "prefetch" call, but we just allow the CPU to schedule tasks on both the comms and comp stream anticipating that the computations will take longer than (and thus hide) communication.

For example, we use checkpointing with offloading so that we are only offloading previously saved tensors, and the chunk of compute is bigger. Another heuristic is that we intentionally do not offload the last output.
