### ISSUE TITLE
gpt-fast vs. torchchat

### ISSUE THREAD

**Issue by austinmw** [pytorch/torchtune#1943]
Hi,

I'm looking into gpt-fast and torchchat for running LLMs on my Mac. I see that gpt-fast works with torchtune, but I'm not sure how it stacks up against torchchat. Also, I've noticed torchtune mentioned in the torchchat repo, but not the other way around. Could you shed some light on comparing the two and how each integrates with torchtune?

Thanks!

**Comment by felipemello1** [comment]
@joecummings , can you help with this question?

**Comment by joecummings** [comment]
Hey @austinmw - great question and glad you're checking out the full suite of PyTorch options!

As mentioned in the gpt-fast repo, it is *not* intended to be a "framework" or "library" - it is intended to show off what kind of performance you can get with native PyTorch. torchchat, on the other hand, is definitely a library that shows off even more options for running LLMs on edge devices. 

Another way in which they differ is the support structure. Since gpt-fast is more of a "demo", requests for bug fixes or new features may take a little longer to implement. torchchat does have some dedicated support so on average, requests are handled quicker. 

Any model finetuned with torchtune can output the model in a Hugging Face-compatible checkpoint, which is supported by *both* gpt-fast and torchchat, so integration is easy!

**Caveat**: Support for some models like Qwen2, Qwen2.5, or Gemma-2 are supported in torchtune, but not yet supported in either torchchat or gpt-fast. If you really want to use these models, you can use a library like [Ollama to run your model on Mac](https://github.com/ollama/ollama#import-from-pytorch-or-safetensors). 

LMK if this helps or if there's anything else we can help you with! The torchchat team is very responsive so I'd also recommend reaching out to them if you decide to go with that option.

**Comment by austinmw** [comment]
Thanks!
