### ISSUE TITLE
Data loader token length?

### ISSUE THREAD

**Issue by binarycrayon** [pytorch/torchtune#558]
Hello, my finetune data has a median of 6000 tokens and 9000 max tokens. what data loader is torch tune using and do I need to specify sequence length for the data set?

How do I calculate memory use in this case?

Thank you!

**Comment by RdoubleA** [comment]
TorchTune is using PyTorch's standard `DataLoader`: https://github.com/pytorch/torchtune/blob/83c06d422ebf686b418faf84f1cc346ea8c4902b/recipes/lora_finetune_single_device.py#L301

As of now, you don't need to specify sequence length in the dataset. We still need to add support for truncating past the maximum sequence length.

Your peak memory usage will likely consist largely of the model instead of the data in your case with 9000 max tokens.

**Comment by binarycrayon** [comment]
Thanks for the pointer! Looking forward to torchtune's future development
