### ISSUE TITLE
[RFC] Documenting and validating recipe params

### ISSUE THREAD

**Issue by RdoubleA** [pytorch/torchtune#648]
## Context
The config system has gone through a couple of iterations, the earliest had a recipe params abstraction which was a convenient location to collect, document, and validate all the parameters needed to run a particular recipe. We've since removed this, favoring an approach where the config is directly connected to the recipe with no additional abstractions in between This gives us a lot of flexibility in defining the exact component we need for a param, but now we lose this self-documenting feature, and it's not obvious where recipe parameter documentation and validation should go.

## The Problem
Ideally, the parameters in the config should be named in a way that is self-explanatory, but this is still not ideal because a user will still need to parse through example configs and see how it is used in recipe code to really understand 1) how it's being used, 2) whether this is required or optional. A case in point was when @joecummings pointed out that not specifying optimizer_in_bwd in a config lead to a recipe breaking because it expected that parameter, but that was not immediately clear. Even if we set a reasonable default for this, it is slightly underhanded because most user configs will not modify this value and will have no idea that this is being set to a certain value. We should be clear and unambiguous what the required params a user must define in a config to run a recipe are and what will have default values that they can leave out.

One approach could be to comment every parameter in our example configs, but these share a lot of parameters and it would get quite overwhelming to contain all this information in the config when it should be a concise overview of how to run a recipe.

## Proposed Approach
Our recipes have two "setup" functions, the standard `__init__` and a separate `setup` method. It is not immediately clear what the distinction between the two is, or why we shouldn't just merge both into `__init__`. We can kill two birds with one stone and delineate these responsibilities for the two methods:

#### `__init__()`
- Unfold all params from the `DictConfig` (assigning them to class variables)
- Document each parameter and note any default values that are used if not found in the `DictConfig`
- Perform any validation of user parameters (i.e., some recipes do not support fp16)

#### `setup()`
- Instantiate the provided parameters
- Any other compute/memory heavy operations to get every ready for the train loop (setup model, optimizer, load checkpoint, etc)

cc @ebsmothers, @rohan-varma, @joecummings since we've had previous discussions around this

**Comment by kartikayk** [comment]
Thanks for putting this together! A few thoughts and comments:

> A case in point was when @joecummings pointed out that not specifying optimizer_in_bwd in a config lead to a recipe breaking because it expected that parameter,

I had a follow up discussion with @joecummings and I think we need have an explicit contract with the users that only configs and recipes registered together (i.e. paired together in ```tune ls```) should be expected to work. If a user is trying to run a config with a recipe that it's not meant to be run, they are expected to run into such issues and we're not responsible for that. For a given recipe, EACH config should contain all of the expected flags. This is a requirement from the recipe developer (us) and these should be documented in the recipe where they are used. We can add comments to configs where necessary but ideally the code is the best documentation for this.

> It is not immediately clear what the distinction between the two is, or why we shouldn't just merge both into __init__

The intent of these two functions is very different. ```__init__``` is setting up all of the recipe state and parameters whereas ```setup``` is responsible for building all of the components such as the model, optimizer and dataset. These are separated out because for most cases, ```__init__``` can be copied over (every recipe should have dtype, device, resume_from_checkpoint```) but the way the components are setup can be different (eg: I may need extra work to setup the tokenizer if I'm not using SPM, or I might have additional setup_model calls if I have teacher and student models). 

> Unfold all params from the DictConfig (assigning them to class variables)

Not a huge fan of this. It's unnecessary because not all params will actually need to be stored as class attributes. Some might just be pass throughs (eg: batch size). Also seems like we're solving the documentation problem but in a round about way (assuming the error issue related to opt_in_bwd for example goes away based on the contract I mentioned above between configs and recipes). I think we can solve the documentation issue through tutorials and comments in the official configs. I actually prefer comments in the configs - makes them more readable.

**Comment by RdoubleA** [comment]
> EACH config should contain all of the expected flags

Then there's no default values? All parameters HAVE to be defined in the config. Let's say we add a new parameter controlling a new feature in a recipe. And say many users have made their own custom configs to run this recipe. This new parameter is now required by the recipe and will immediately break all user configs. We will also have to update all of our configs with the new parameter (which may be ok if our # configs per recipe remains small, but with more and more models this may get more difficult)

> This is a requirement from the recipe developer (us) and these should be documented in the recipe where they are used

The problem is the config parameters are used throughout the recipe... so unless we have a docstring at the top that describes every parameter that is used, it will be a wild hunt to find what each parameter actually does. Maybe I can get behind comments in the config...

**Comment by joecummings** [comment]
>  > Unfold all params from the DictConfig (assigning them to class variables)

> Not a huge fan of this. It's unnecessary because not all params will actually need to be stored as class attributes. Some might just be pass throughs (eg: batch size). 

I'm actually hugely in favor of unfolding as many params as possible into class variables. I already found a bug in which optimizer in backwards was being set on the class variable, but referenced via config later on in the script. So any action taken on the class variable was not persisted. If we declare best practices as setting class variables from config in the init, and then, discarding the config, so that the source of truth is the class itself, we will avoid headaches down the road. 

For things like checkpointer, we can set a class variable like self._checkpointer_cfg so we don't unfold everything individually.

**Comment by joecummings** [comment]
> I actually prefer comments in the configs - makes them more readable. And of course more comments in the recipes.

Comments in the configs are a good starting point, but I worry about them getting out-of-date and out-of-sync quickly. Because so many variables are shared between configs, if you want to update one of them, you have to go through and update them all and it's easy to miss one as the number of recipe configs we have expands. Maybe we do short comments in the config and consider a master list somewhere with more details on each variable that can possibly be in a config. This would be hosted in our documentation and include examples of how to use each variable as well.

**Comment by joecummings** [comment]
> Then there's no default values? All parameters HAVE to be defined in the config. Let's say we add a new parameter controlling a new feature in a recipe. And say many users have made their own custom configs to run this recipe. This new parameter is now required by the recipe and will immediately break all user configs. We will also have to update all of our configs with the new parameter (which may be ok if our # configs per recipe remains small, but with more and more models this may get more difficult)

BC is going to be a huge issue, especially once we start relying on PyPI installs rather than `git clone` installs. I think there's a couple of options: 1) Any new params added to a recipe after a major release have a default or 2) we provide some way to people to update recipes and configs without updating their package. This would mean we have a separate "hub" of recipes and configs, which I'm in favor for long-term.

**Comment by RdoubleA** [comment]
> I think we currently have the convention (or at least this was the intention) that configs should not be referred in anything other than __init__ or setup.

Seems we're in alignment that configs should be unfolded in the `__init__` anyway and class variables made where it makes sense. But this doesn't directly address the documentation problem.

> Like adding BS to self._batch_size won't buy anything?

If creating this class variable so that `_setup_data()` can use it later and we can adhere to our conventions of unfolding configs in init and a clear distinction between init and setup, then I don't see any harm in making this variable.

> Comments in the configs are a good starting point, but I worry about them getting out-of-date and out-of-sync quickly. Because so many variables are shared between configs, if you want to update one of them, you have to go through and update them all and it's easy to miss one as the number of recipe configs we have expands.

Good point, I think it doesn't hurt to have short comments in the config (for things like optimizer_in_bwd, which I still don't know what it does :) ) but most parameters are self-explanatory. We should also have the master list in the recipe docstring or have it point to a tutorial, since I don't think pydoclint will parse it correctly if it only takes in a DictConfig.

> IMO just adding defaults wont solve the problem since some combination of params just might not make sense and even if you have defaults you might cause breakages or worse - silent errors

Thinking about this more, I agree... if all new features start getting defaults then the config no longer becomes a source of truth. I'm almost inclined to go to the extreme of saying no defaults for flat params (except for components/builders). I'm more in favor of versioning (since recipes won't be updated until major releases anyway, besides bug fixes) and adding a warning to users to use the updated recipe if they're still using a deprecated one.

> I think this is hell-city.

What does this look like :)

**Comment by RdoubleA** [comment]
Closing this as stale and not currently needed
