### ISSUE TITLE
Generate with KV-cache enabled vs. not enabled gives different results

### ISSUE THREAD

**Issue by joecummings** [pytorch/torchtune#959]
We would expect that the only different between enabling a kv-cache for a model in generation is the speed of decoding; however, in experiments with commenting out `with device: model.setup_caches()` in our generate.py recipe, the output is garbage.

Needs more investigation.

**Comment by rohan-varma** [comment]
You might need to change the `incremental_decode` in the generation function?

**Comment by calvinpelletier** [comment]
@joecummings I'm guessing this is because the causal mask is created in `setup_caches()` [here](https://github.com/pytorch/torchtune/blob/main/torchtune/modules/transformer.py#L171), so without calling this function we're attending to all tokens, resulting in garbage outputs. Maybe we should move this mask initialization into `__init__`?
