### ISSUE TITLE
Is it possible to full fine tuning llama3 70B with torchtune on a machine with 8*A100 80G ?

### ISSUE THREAD

**Issue by jaywongs** [pytorch/torchtune#987]
I'm not sure if it's possible. The document didn't mention that, perhaps?

**Comment by RdoubleA** [comment]
Hi @jaywongs, you are more than well equipped to run any of our recipes with that configuration :) our documentation mentions some common hardware that users may run recipes with, anything beefier than what's mentioned should certainly be good

**Comment by jaywongs** [comment]
> Hi @jaywongs, you are more than well equipped to run any of our recipes with that configuration :) our documentation mentions some common hardware that users may run recipes with, anything beefier than what's mentioned should certainly be good

Thank for your quick reply!
I apologize for the confusion. What I actually meant was a full fine-tuning, but not specifically Lora or QLora.

**Comment by ebsmothers** [comment]
@jaywongs yep you should be able to without any problems. Just give 

```
tune run --nproc_per_node 4 full_finetune_distributed --config llama3/8B_full
```

a try (after downloading the model). Or if you want you can go all the way to `--nproc_per_node 8` to get larger batch size(/faster training).

**Comment by kartikayk** [comment]
@jaywongs If you're talking about 70B, then this should also be possible. I use the following config (with the PagedAdamW optimizer from bitsandbytes) with the Llama2 70B model for full finetuning which takes ~51GB of memory on 8 80GB A100s. So this should be able to handle the larger vocab size with Llama3 70B as well. You'll need to make some updates including pointing to the right checkpoint files and dir etc. Let me know if this works for you.

**Comment by rohan-varma** [comment]
@kartikayk Is there a config linked? Don't think we can use PagedAdamW with FSDP unfortunately

**Comment by kartikayk** [comment]
@rohan-varma yeh I copied the config in the gist above. I've been training 70B full with this setting for Llama2 (screenshot attached)

<img width="1026" alt="Screenshot 2024-05-16 at 6 56 02 PM" src="https://github.com/pytorch/torchtune/assets/47255723/9560c493-1a0d-4571-b328-9c6c2d3258aa">


> Don't think we can use PagedAdamW with FSDP unfortunately

I dont think this is true? BnB had a recent release which supports FSDP, though 8-bit is WIP. I think this should extend to Llama3 as well since it takes ~52GB of memory.

**Comment by jaywongs** [comment]
Thank you so much, i'll give it a try!

> @jaywongs If you're talking about 70B, then this should also be possible. I use the following config (with the PagedAdamW optimizer from bitsandbytes) with the Llama2 70B model for full finetuning which takes ~51GB of memory on 8 80GB A100s. So this should be able to handle the larger vocab size with Llama3 70B as well. You'll need to make some updates including pointing to the right checkpoint files and dir etc. Let me know if this works for you.
> 
> Link: https://gist.github.com/kartikayk/a9bea0cca013a0f75e8859ad3250013c

**Comment by rohan-varma** [comment]
> @rohan-varma yeh I copied the config in the gist above. I've been training 70B full with this setting for Llama2 (screenshot attached)
> 
> <img alt="Screenshot 2024-05-16 at 6 56 02 PM" width="1026" src="https://private-user-images.githubusercontent.com/47255723/331433387-9560c493-1a0d-4571-b328-9c6c2d3258aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5Mjg5MzgsIm5iZiI6MTcxNTkyODYzOCwicGF0aCI6Ii80NzI1NTcyMy8zMzE0MzMzODctOTU2MGM0OTMtMWEwZC00NTcxLWIzMjgtOWM2YzJkMzI1OGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA2NTAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhOWU3MjM3MDc5NmM5ZTNiMzg2N2IyNWI4Y2ZlMGZmY2MxZTkwNWZmODAxNTJhY2Q4NzE5YjgwODQyNGE2MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KsN5YdkYMq2L4WxdMAXQC6-bkmQld_9bz7pDDyo81Rg">
>  
> 
> > Don't think we can use PagedAdamW with FSDP unfortunately
> 
> I dont think this is true? BnB had a recent release which supports FSDP, though 8-bit is WIP. I think this should extend to Llama3 as well since it takes ~52GB of memory.

Oh ok, I think perhaps the initial version of the comment didn't have the gist linked.

Curious if you've tried optimizer state save / load with FSDP + bnb optimizers? Last @ebsmothers and I checked, this was failing, which is why the bnb optimizers weren't shipped in any of the llama3 recipes, even though they helped memory.

**Comment by rohan-varma** [comment]
That sounds good. If we do ship such a recipe, we should be careful to document that the 8 bit low precision optimizers aren't supported, because it'll be pretty easy for users to swap about PagedAdamW for PagedAdamW8bit and not realize checkpointing will break. This is of course still possible in today's set up, so perhaps we should just hard error for now when FSDP + low precision optimizer is detected.

**Comment by rohan-varma** [comment]
@kartikayk @ebsmothers Have you been able to train llama3-70b on 8xA100 without CPU offload? Even with PagedOptimizer, I'm getting an OOM in the backward pass so think we need CPU offload for llama3-70b at least.

**Comment by ebsmothers** [comment]
@rohan-varma I haven't run it myself so would defer to your experience here.

**Comment by felipemello1** [comment]
Closing it since now are support 70b. Please feel free to support if there are any questions! thanks :)

https://github.com/pytorch/torchtune/blob/6f37d15b2c99d49ca926173455569aa6f8e24d9d/recipes/configs/llama3/70B_full.yaml#L9
